name: Build container image

on:
  workflow_dispatch:
    inputs:
      openstack_base_image:
        type: string
        description: "OpenStack Swift base image"
        default: quay.io/openstack.kolla/swift-base
      openstack_base_image_tag:
        type: string
        description: "OpenStack Swift base image tag (e.g. '2024.1-rocky-9')"
        default: 2024.1-rocky-9

env:
  REGISTRY: quay.io
  IMAGE_NAME: nimbolus/openstack-kolla-swift-health-exporter

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.QUAY_IO_USERNAME }}
          password: ${{ secrets.QUAY_IO_TOKEN }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          build-args: |
            OPENSTACK_BASE_IMAGE=${{ inputs.openstack_base_image }}
            OPENSTACK_BASE_IMAGE_TAG=${{ inputs.openstack_base_image_tag }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.openstack_base_image_tag }}
